pipeline {
    agent any
    stages{
        stage("Checkout") {
            steps {
                checkout scm
            }
        }
        stage("npm install") {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                echo "buildstep"
            }
        }
        stage('Deploy') {
            steps{
                echo "deploystep"
            }
        }
    }
}