pipeline {
    agent any
    stages{
        stage("Checkout") {
            steps {
                checkout scm
            }
        }
        stage("npm install") {
            steps {
                sh '''curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
                export NVM_DIR="$HOME/.nvm"
                [ -s "$NVM_DIR/nvm.sh" ] && \\. "$NVM_DIR/nvm.sh"
                nvm install 20
                cd ./weather-webpage/src/
                npm install
                npm run'''
            }
        }
        stage('Build') {
            steps {
                echo 'step'
            }
        }
        stage('Deploy') {
            steps{
                echo "deploystep"
            }
        }
    }
}
